- name: put initial awslogs config
  template:
    src: awslogs.{{ role }}.conf
    dest: /tmp/awslogs.conf
    mode: 644
  when: role in ("app", "job",)

- name: download awslogs setup scripts
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py

- name: download AgentDependencies
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/AgentDependencies.tar.gz
    dest: /tmp/AgentDependencies.tar.gz

- name: extract AgentDependencies.tar.gz
  unarchive:
    src: /tmp/AgentDependencies.tar.gz
    dest: /tmp/
    remote_src: yes

- name: install awslogs
  shell: /usr/bin/python3 /tmp/awslogs-agent-setup.py -n -r ap-northeast-1 --dependency-path /tmp/AgentDependencies -c /tmp/awslogs.conf
  notify: enable awslogs
