version: 0.0
os: linux
files:
  - source: /
    destination: /root/jaaxman
  - source: README.md
    destination: /opt
hooks:
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 600
      runas: root
