version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jaaxman-backend
    container_name: jaaxman-backend
    depends_on:
      - mysql
      - xray
    environment:
      RUN_MODE: development
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_HOST: mysql
      AWS_XRAY_DAEMON_ADDRESS: xray:2000
      ASSETS_BASE_URL: http://localhost:8001/assets/
      API_TOKEN:
      GOOGLE_API_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      SLACK_URL:
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
    networks:
      app:
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "uwsgi --ini /app/uwsgi.ini --py-autoreload=1"
  frontend:
    image: node:8.12
    container_name: jaaxman-frontend
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    working_dir: /app/frontend
    command: bash -c "npm install && npm start"
  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    image: jaaxman-nginx
    container_name: jaaxman-nginx
    depends_on:
      - backend
    networks:
      app:
    ports:
      - "8080:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx/jaaxman.conf:/etc/nginx/conf.d/jaaxman.conf:ro
      - ./backend/app:/app/app:ro
  mysql:
    image: mysql:5.6
    container_name: jaaxman-mysql
    environment:
      MYSQL_DATABASE: jaaxman
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      app:
    ports:
      - "3336:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/initdb:/docker-entrypoint-initdb.d
  xray:
    image: pottava/xray:3.0
    container_name: jaaxman-xray
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      app:
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"
    command: --region ap-northeast-1 --local-mode

volumes:
  db_data:

networks:
  app:
