version: 2
jobs:
  python-test:
    working_directory: ~/jaaxman
    docker:
      - image: circleci/python:3.6.2
        environment:
          RUN_MODE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_HOST: 127.0.0.1
          GOOGLE_API_KEY: ""
      - image: mysql:5.6
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Start test
          command: |
            . venv/bin/activate
            sleep 5s
            coverage run manage.py test
      - run:
          name: Report coverage
          command: |
            . venv/bin/activate
            coverage report

  build-assets:
    working_directory: ~/jaaxman
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          # command: npm run build:$CIRCLE_BRANCH
          command: npm run build:production
      - save_cache:
          key: build-assets-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./app/static/dist

  deploy:
    working_directory: ~/jaaxman
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install extra pip packages for build
          command: |
            . venv/bin/activate
            pip install wheel
            pip install awscli
      - run:
          name: Create pip wheels
          command: |
            . venv/bin/activate
            pip wheel -w wheelhouse -r requirements.txt
      - restore_cache:
          key: build-assets-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Send app tarball to S3
          command: |
            IDENTIFIER=`date '+%Y%m%d%H%M%S'`
            TAR_NAME=jaaxman-${IDENTIFIER}.tar.gz
            tar cvzf $TAR_NAME --exclude=venv --exclude=app/static/dist/*.js *
            . venv/bin/activate
            aws s3 cp $TAR_NAME s3://jaaxman-production-infla/app/
            aws s3 sync ./app/static/dist/ s3://jaaxman-production-infla/assets/js/$IDENTIFIER --exclude=manifest.json

workflows:
  version: 2
  test_and_build:
    jobs:
      - python-test
      - build-assets:
          requires:
            - python-test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - python-test
            - build-assets
          filters:
            branches:
              only:
                - master
