pip:
  restore_cache: &pip_restore_cache
    keys:
      - pip-v2-{{ .Branch }}-{{ checksum "backend/requirements-dev.txt" }}-{{ checksum "backend/requirements.txt" }}
      - pip-v2-{{ .Branch }}-
      - pip-v2-

  install:  &pip_install
    name: Install pip packages
    command: |
      python3 -m venv ~/venv
      . ~/venv/bin/activate
      pip install -r backend/requirements-dev.txt

  save_cache: &pip_save_cache
    key: pip-v2-{{ .Branch }}-{{ checksum "backend/requirements-dev.txt" }}-{{ checksum "backend/requirements.txt" }}
    paths:
      - ~/venv

version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/jaaxman
jobs:
  python-test:
    executor: python
    docker:
      - image: circleci/python:3.6.5
        environment:
          RUN_MODE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_HOST: 127.0.0.1
          GOOGLE_API_KEY: ""
      - image: mysql:5.6
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run tests
          command: |
            . ~/venv/bin/activate
            sleep 5s
            cd backend/
            coverage run manage.py test
      - run:
          name: Report coverage
          command: |
            . ~/venv/bin/activate
            cd backend/
            coverage report

  flake8:
    executor: python
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run flake8
          command: |
            . ~/venv/bin/activate
            flake8 ./backend

workflows:
  version: 2
  test:
    jobs:
      - python-test
      - flake8
