# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rssfetchhistory_is_duplicated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(related_name='papers', related_query_name='paper', to='app.Author'),
        ),
    ]
