# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
