# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170812_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfetchhistory',
            name='is_duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
