# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models

DEFAULT_SUBMIT_TYPE = 'default'
SUBMIT_TYPES = (
    ('new', 'NEW'),
    ('updated', 'UPDATED'),
    ('cross_listed', 'CROSS LISTED'),
)


def set_submit_type(paper):
    for submit_type, submit_type_title in SUBMIT_TYPES:
        if paper.title.endswith(f'{submit_type_title})'):
            paper.submit_type = submit_type
    if paper.submit_type == DEFAULT_SUBMIT_TYPE:
        paper.submit_type = SUBMIT_TYPES[0][0]
    return paper


def migrate_submit_type(apps, schema_editor):
    Paper = apps.get_model('app', 'Paper')
    db_alias = schema_editor.connection.alias
    for paper in Paper.objects.using(db_alias).all():
        paper = set_submit_type(paper)
        paper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170820_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='submit_type',
            field=models.CharField(default=DEFAULT_SUBMIT_TYPE, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_submit_type)
    ]
