# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 17:44
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_cross_listed(apps, schema_editor):
    Paper = apps.get_model('app', 'Paper')
    db_alias = schema_editor.connection.alias
    for paper in Paper.objects.using(db_alias).all():
        if paper.submit_type == 'cross_listed':
            paper.is_cross_listed = True
            paper.submit_type = 'new'
            paper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_paper_submit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_cross_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_cross_listed)
    ]
